version: "3.6"
services:
  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: 'gitlab.barbunicorn.gay'
    volumes:
      - gitlab_data:/var/opt/gitlab
      - /var/logs/gitlab/:/var/log/gitlab/
      - /srv/gitlab/:/etc/gitlab
    shm_size: 256m
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host("gitlab.barbunicorn.gay")
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.tls.certresolver=barbResolver

volumes:
  gitlab_data:

networks:
  proxy:
    external: true
