version: "3"
services:
  mailserver:
    container_name: mailserver
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: barbunicorn.gay
    env_file: files/mailserver.env
    volumes: 
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  mail_data:
  mail_state:
