version: '3'

services:
  traefik:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/traefik:/etc/traefik:ro
      - /var/log/traefik:/var/log
    networks:
      - proxy
    environment:
      DOCKER_HOST: dockersocket
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  proxy:
    external: true
