version: "3.6"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus:uid=nobody,gid=nobody
    networks:
      - proxy
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - proxy
    volumes:
      - grafana_data:/var/lib/grafana
      - /srv/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - /var/log/grafana:/var/log/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host("grafana.barbunicorn.gay")
      - traefik.http.routers.grafana.tls.certresolver=barbResolver
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  proxy:
    external: true
