version: "2.2"
services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - proxy
    cpus: 0.05
    mem_limit: 5g
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "65534:65534"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--log.level=debug'
    networks:
      - proxy
    restart: unless-stopped
    cpus: 0.05
    mem_limit: 5g
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host("prometheus.barbunicorn.gay")
      - traefik.http.routers.prometheus.service=prometheus
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus.tls.certresolver=barbResolver
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - proxy
    volumes:
      - grafana_data:/var/lib/grafana
      - /srv/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - /var/log/grafana:/var/log/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host("grafana.barbunicorn.gay")
      - traefik.http.routers.grafana.tls.certresolver=barbResolver
    cpus: 0.05
    mem_limit: 5g

volumes:
  prometheus_data:
  grafana_data:

networks:
  proxy:
    external: true
