version: "2.2"
services:
  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: 'gitlab.barbunicorn.gay'
    volumes:
      - gitlab_data:/var/opt/gitlab
      - /var/logs/gitlab/:/var/log/gitlab/
      - /srv/gitlab/:/etc/gitlab
    shm_size: 256m
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host("gitlab.barbunicorn.gay")
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.tls.certresolver=barbResolver

      - traefik.http.routers.registry.rule=Host("registry.barbunicorn.gay")
      - traefik.http.services.registry.loadbalancer.server.port=5050
      - traefik.http.routers.registry.service=registry
      - traefik.http.routers.registry.tls.certresolver=barbResolver
    cpus: 0.2
    mem_limit: 5g
  gitlab_runner:
    container_name: gitlab_runner
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_data:/home/gitlab-runner
      - gitlab_runner_docker:/root/.docker/machine
    cpus: 0.2
    mem_limit: 5g

volumes:
  gitlab_data:
  gitlab_runner_data:
  gitlab_runner_docker:

networks:
  proxy:
    external: true
