version: "2.2"
services:
  httpserver:
    container_name: httpserver
    image: nginx:latest
    restart: always

    labels:
      - traefik.enable=true
      - traefik.http.routers.httpserver.rule=Host("www.barbunicorn.gay")
      - traefik.http.routers.httpserver.tls.certresolver=barbResolver
    volumes:
      - /srv/nginx/barbunicorn/:/usr/share/nginx/html:ro
    networks:
      - proxy
    cpus: 0.2
    mem_limit: 5g

networks:
  proxy:
    external: true
