version: "2.2"
services:
  httpserver:
    container_name: httpserver
    image: nginx:latest
    restart: always

    labels:
      - traefik.enable=true

      - traefik.http.routers.http-httpserver.rule=Host("www.barbunicorn.gay", "barbunicorn.gay")
      - traefik.http.routers.http-httpserver.entrypoints=web
      - traefik.http.routers.http-httpserver.middlewares=https@file

      - traefik.http.routers.httpserver.rule=Host("www.barbunicorn.gay", "barbunicorn.gay")
      - traefik.http.routers.httpserver.entrypoints=websecure
      - traefik.http.routers.httpserver.tls.certresolver=barbResolver
    volumes:
      - /srv/nginx/barbunicorn/:/usr/share/nginx/html:ro
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy
    cpus: 0.2
    mem_limit: 5g

networks:
  proxy:
    external: true
