version: "3"
services:
  mailserver:
    container_name: mailserver
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: barbunicorn.gay
    env_file: files/mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - /srv/mail/config/:/tmp/docker-mailserver
      - /srv/mail/letsencrypt:/etc/letsencrypt
      - /srv/mail/barbunicorn.crt:/certs/barbunicorn.gay.crt
      - /srv/mail/barbunicorn.key:/certs/barbunicorn.key
      - /var/log/mail/:/var/log/mail/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  mail_data:
  mail_state:
