
version: "2.2"

services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /srv/valheim/config:/config
      - /srv/valheim/data:/opt/valheim
    ports:
      - 2456-2458:2456-2458/udp
    env_file:
      - /srv/valheim/valheim.env
    restart: always
    stop_grace_period: 2m
    cpus: "0.2"
    mem_limit: 5g
