
version: "3"

services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /srv/valheim/config:/config
      - /srv/valheim/data:/opt/valheim
    ports:
      - 2456-2458:2456-2458/udp
    restart: always
    stop_grace_period: 2m
