entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

providers:
  file:
    directory: /etc/traefik/providers
    watch: true

log:
  filePath: "/var/log/traefik.log"
  level: DEBUG

api:
  dashboard: true

