http:
  routers:
    http_dashboard:
      rule: Host("traefik.barbunicorn.gay")
      service: api@internal
      entrypoints:
        - web
      middlewares:
        - https
    dashboard:
      rule: Host("traefik.barbunicorn.gay")
      tls:
        certResolver: barbResolver
      entrypoints:
        - websecure
      service: api@internal
      middlewares:
        - auth

  middlewares:
    https:
      redirectScheme:
        scheme: https
    auth:
      basicAuth:
        users:
          - %%USER_PASSWORD%%
